version: '3.7'

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - pet-sitter1
      - pet-sitter2
    cpus: 0.1
    mem_limit: 256M
  pet-sitter1: &pet-sitter
    hostname: pet-sitter1
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    expose:
      - "3000"
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - postgres
    cpus: 1
    mem_limit: 1024M
  pet-sitter2:
    <<: *pet-sitter
    hostname: pet-sitter2
  postgres:
    ports:
      - 5432:5432
    env_file:
      - .env  
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    container_name: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: ./Dockerfile.pg
    restart: always  
    cpus: 0.5
    mem_limit: 512M

volumes:
  pg-data:
