name: Test unit
on:
  workflow_call:

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      - name: Instala dependencias
        run: yarn install --ignore-engines
      - name: Run teste unitario
        run: yarn test
        

